<?php
$all_residents = [
    ["/303", "Deep Ewing Show", "", "/wp-content/uploads/2023/12/303.jpg", "deep-ewing-show"],
    ["aairs (Seconde Aride & risolee)", "Twin Picks", "", "/wp-content/uploads/2024/09/AAIRS-scaled.jpg", "aairs"],
    ["Aber", "Sweet Furious Animals", "", "/wp-content/uploads/2023/12/ABER.jpg", "sweet-furious-animals"],
    ["ACIDEPLASTIQUE & JUNOL", "SYSTEM OF A DAWN", "", "", "system-of-a-dawn"],
    ["Aimée", "Everything in between", "", "/wp-content/uploads/2024/09/Aimee.jpg", "everything-in-between"],
    ["AUDREY CRISTEA", "MELATONINE OBSESSIONS", "", "/wp-content/uploads/2024/09/audrey-cristea.jpg", "elatonine-obsessions"],
    ["Araxie", "Loaded", "", "", "loaded"],
    ["B-Side", "Miniteuf", "", "", "miniteuf"],
    ["BAUME", "TOUT QUITTER POUR PARTIR", '', "/wp-content/uploads/2023/12/BAUME.jpg", "tout-quitter-pour-partir"],
    ["BAXUA AND WAVEY CUTS", "FRACAS", "", "/wp-content/uploads/2023/12/BAXUA-_-WAVEY-CUTS.jpg", "fracas"],
    ["BELARIA", "VAGUES SYNTHETIQUES", '', "/wp-content/uploads/2023/12/BELARIA.jpg", "vagues-synthétiques"],
    ["BLANCA BRUSCI", "Poetic Weapons", "", "/wp-content/uploads/2023/12/BLANCA-BRUSCI.jpg", "poetic-weapons"],
    ["BOBOXA", "Mind The Gap", "", "/wp-content/uploads/2023/12/BOBOXA.jpg", "mind-the-gap"],
    ["BROSKI", "EXPÉDITION ÉLECTRONIQUE", "", "/wp-content/uploads/2023/12/BROSKI.jpg", "expéditions-électroniques"],
    ["Carole Fe", "Natural High", "", "/wp-content/uploads/2024/09/CaroleFe-NaturalHigh.jpg", "natural-high"],
    ["CHARLEEPS", "RIVIERA EXPRESS", "", "/wp-content/uploads/2023/12/CHARLEEPS.jpg", "riviera-express"],
    ["Collettivo Loredana", "Corrente", "", "/wp-content/uploads/2024/09/CORRENTE.jpg", "corrente"],
    ["DISCOSTOUF", "PROG INTAKE", "", "/wp-content/uploads/2024/09/discostouf-scaled.jpeg", "prog-intake"],
    ["Eerie", "MUSIC FOR READING BOOKS", "", "/wp-content/uploads/2024/09/EERIE.jpg", "music-for-reading-books"],
    ["ELI", "SEXY LOVE BEACH", "", "/wp-content/uploads/2024/09/ELI-scaled.jpeg", "sexy-love-beach"],
    ["ELONA PRIME", "SMALL SEEDS", "", "/wp-content/uploads/2023/12/ELONA-PRIME.jpg", "small-seeds"],
    ["ELONA", "COFFEE VIBE", "", "/wp-content/uploads/2023/12/ELONA-PRIME.jpg", "coffe-vibe"],
    ["Ensemble", "Ensemble Podcast", "", "/wp-content/uploads/2023/12/ENSEMBLE-PODCAST.jpg", "ensemble-podcast"],
    ["FELIX", "SONORAMA", "", "/wp-content/uploads/2023/12/FELIX.jpg", "sonorama"],
    ["FORMATS", "SOUNDSCAPE SERIES", "", "/wp-content/uploads/2024/09/FORMATS.jpg", "soundscape-series"],
    ["Genou Fragile", "Cataplasme", "", "/wp-content/uploads/2023/12/GENOU-FRAGILE.jpg", "cataplasme"],
    ["GIRASOL", "LATITUDES LUNATIQUES", '', "/wp-content/uploads/2023/12/GIRASOL.jpg", "latitudes-lunatiques"],
    ["H2O", "Deep Dive", "", "/wp-content/uploads/2023/12/H2O.jpg", "deep-dive"],
    ["HAINERVÉ", "TRANQUILLEMENT", "", "/wp-content/uploads/2024/09/Hainerve.jpg", "tranquillement"],
    ["Jabu Noir", "The Color Of Cajá", "", "/wp-content/uploads/2024/09/JABU-NOIR-1-e1726578188739.jpg", "the-color-of-cajá"],
    ["JAN ASTASIA", "Face A/B", "", "/wp-content/uploads/2023/12/JAN-ASTASIA.jpg", "face-ab"],
    ["Julo Julo", "Contemplation", "", "/wp-content/uploads/2023/12/JULO-JULO.jpg", "contemplation"],
    ["KENZZZA", "Silky witchcraft", "", "/wp-content/uploads/2023/12/KENZZZA.jpg", "silky-witchcraft"],
    ["Krema Krew", "Cosmic Tales", "", "", "cosmic-tales"],
    ["KICK21","MIXED SIGNALS",  "", "/wp-content/uploads/2024/09/kick21.jpg", "mixed-signals"],
    ["KIM KENIS", "Same As It Ever Was", "", "/wp-content/uploads/2023/12/KIM-KENIS.jpg", "same-as-it-ever-was"],
    ["L/MA0RI", "Monde Magique", "", "/wp-content/uploads/2024/09/L-MA0RI.jpg", "monde-magique"],
    ["MARIE NONNIS & DARIUS ZOLTAN", "ÉCLAT SONORE", "", "/wp-content/uploads/2024/09/marie-nonnis-darius-zoltan-1.jpg", "éclat-sonore"],
    ["MARS O10C", "BREAK A LEG", "", "/wp-content/uploads/2023/12/MARS-O10C.jpg", "break-a-leg"],
    ["MATSO", "ADN", "", "/wp-content/uploads/2023/12/MATSO.jpg", "adn"],
    ["MAX KLANK", "TAR", "", "/wp-content/uploads/2023/12/MAX-KLANK.jpg", "tar"],
    ["Mesma Records","Mesmarized", "", "/wp-content/uploads/2024/09/Mesma.jpg", "mesmarized"],
    ["MICROPOLIS", "MACROPHONE", "", "/wp-content/uploads/2023/12/MICROPOLIS.jpg", "macrophone"],
    ["MIMI", "FAUTEUIL CLUB", '', "/wp-content/uploads/2023/12/MIMI-S.jpg", "fauteuil-club"],
    ["MONACO GZA", "Dschungel Kosmos", "", "/wp-content/uploads/2023/12/MONACO-GZA.jpg", "dschungel-kosmos"],
    ["MOTORIUM", "Motorium Botanic", "", "/wp-content/uploads/2024/09/MOTORIUM.jpg", "motorium-botanic"],
    ["Neju", "Habiter le midi", "", "/wp-content/uploads/2024/09/NEJU-credit-Berat-Nalci-scaled.jpg", "habiter-le-midi"],
    ["NOFRAJE", "GLOBAL FREQUENCY", '', "/wp-content/uploads/2023/12/NOFRAJE.jpg", "global-frequency"],
    ["OLGA B.", "KOMMUNALKA", "", "/wp-content/uploads/2024/09/Olga-B.-Kommunalka-scaled.jpeg", "kommunalka"],
    ["PARADIS FISCAL", "Synthetic Music Company", "", "/wp-content/uploads/2023/12/PARADIS-FISCAL.jpg", "synthetic-music-company"],
    ["Perceval", "WE NEED JUNGLE I'M AFRAID", "", "/wp-content/uploads/2024/09/WE-NEED-JUNGLE-I_M-AFRAID.png", "we-need-jungle-i'm-afraid"],
    ["PLANISPHERE", "MUSIQUES POUR MOBILIER", '', "/wp-content/uploads/2023/12/PLANISPHERE.jpg", "musiques-pour-mobiliers"],
    ["Poiçon", "Bande Désorganisée", "", "", "bande-désorganisée"],
    ["POMO", "ULTRASOFTCARE", "", "/wp-content/uploads/2024/09/POMO.jpg", "ultrasoftcare"],
    ["Ricky Minaj", "Weirdos 98", "", "", "weirdos-98"],
    ["RODRIGUE SOULGROOVE", "LE SILLON", "", "/wp-content/uploads/2023/12/RODRIGUE.jpg", "le-sillon"],
    ["SAINT MISERE", "NEW PHONE. WHO DIS ?", "", "/wp-content/uploads/2023/12/SAINT-MISERE.jpg", "new-phone-who-dis?"],
    ["SBN6", "Lovecast", "", "/wp-content/uploads/2023/02/SBN6-lovecast-ep2.png", "lovecast"],
    ["SHYPURIAN", "Find Yourself", "", "/wp-content/uploads/2024/09/SHYPURIAN-FIND-YOURSELF-scaled.jpeg", "find-yourself"],
    ["SLIM SLIM", "Hot Chose", "", "/wp-content/uploads/2023/12/SLIM-SIM.jpg", "hot-chose"],
    ["SUNAAS", "SLOW DOWN A MINUTE", '', "/wp-content/uploads/2023/12/SUNAAS.jpg", "slow-down-a-minute"],
    ["Suspicious Noise Upstairs", "Kinky Bonito", "", "/wp-content/uploads/2024/09/kinky-bonito.jpeg", "suspicious-noise-upstairs"],
    ["TAKA", "GOGUETTE ASTRALE", "", "/wp-content/uploads/2023/12/TAKA.jpg", "goguette-astrale"],
    ["Thaïs", "emotional waves", "", "/wp-content/uploads/2024/09/THAIS-EMOTIONAL-WAVES-scaled.jpg", "emotional-waves"],
    ["TOM COOLOLO", "ARTEFACTS AUDITIFS", "", "/wp-content/uploads/2023/12/TOM-COOLOLO.jpg", "artefacts-auditifs"],
    ["TONI DOG", "ÂMES SENSIBLES", "", "/wp-content/uploads/2023/12/TONI-DOG.jpg", "ames-sensibles"],
    ["TROPICALITES", "TRANSATLANTIQUES", "", "/wp-content/uploads/2023/12/TROPICALITES.jpg", "transatlantiques"],
    ["WAVEY CUTS", "Aint Easy Being Wavey", "", "/wp-content/uploads/2023/12/WAVEY-SC.jpg", "aint-easy-being-wavey"],
];